(()=>{
const q=s=>document.querySelector(s);let row=0;
function ensure(){state.eightMusicAssignments=state.eightMusicAssignments||{};state.audioTimeline=state.audioTimeline||{clips:[],zoom:1,snap:'beat'};state.audioTimeline.clips=state.audioTimeline.clips||[]}
function spe(){return 8*60/(Number(state.targetBpm)||147)}
function find(r){ensure();return Object.values(state.eightMusicAssignments).find(a=>r>=a.startRow&&r<=a.endRow)}
function dialog(){if(q('#musicEightDlg'))return;const d=document.createElement('dialog');d.id='musicEightDlg';d.innerHTML=`<form method="dialog" style="min-width:560px;padding:20px;background:#0d1728;color:#fff"><h2>Lisää musiikki kaseihin</h2><p>Valitse kappale ja kasiväli. Aikajanan clippi tehdään automaattisesti.</p><div style="display:grid;grid-template-columns:2fr 1fr 1fr;gap:10px"><label>Kappale<select id="meTrack"></select></label><label>Alkukasi<input id="meStart" type="number" min="1"></label><label>Loppukasi<input id="meEnd" type="number" min="1"></label></div><p id="meInfo"></p><menu style="display:flex;gap:8px;justify-content:flex-end"><button value="cancel" class="btn secondary">Peruuta</button><button type="button" id="meRemove" class="btn secondary">Poista</button><button type="button" id="meApply" class="btn primary">Lisää kaseihin</button></menu></form>`;document.body.appendChild(d);q('#meApply').onclick=apply;q('#meRemove').onclick=remove;q('#meTrack').onchange=info;q('#meStart').oninput=info;q('#meEnd').oninput=info}
function fill(name=''){const s=q('#meTrack');s.innerHTML='<option value="">Valitse musiikki…</option>';for(const t of(state.tracks||[])){const o=document.createElement('option');o.value=t.name;o.textContent=t.name;s.appendChild(o)}if(name)s.value=name}
function info(){const s=Number(q('#meStart').value)||1,e=Math.max(s,Number(q('#meEnd').value)||s),n=e-s+1,name=q('#meTrack').value,a=state.trackAnalysis?.[name];q('#meInfo').textContent=`${n} kasia · ${(n*spe()).toFixed(2)} s${a?.bpm?` · ${Number(a.bpm).toFixed(1)} → ${state.targetBpm} BPM`:''}`}
function open(r){ensure();dialog();row=r;const a=find(r);fill(a?.trackName);q('#meStart').max=q('#meEnd').max=state.eights.length;q('#meStart').value=(a?.startRow??r)+1;q('#meEnd').value=(a?.endRow??r)+1;q('#meRemove').disabled=!a;info();q('#musicEightDlg').showModal()}
function drop(a){if(!a)return;delete state.eightMusicAssignments[a.id];state.audioTimeline.clips=state.audioTimeline.clips.filter(c=>c.assignmentId!==a.id);for(let i=a.startRow;i<=a.endRow&&i<state.eights.length;i++)if(state.eights[i].music===a.trackName)state.eights[i].music=''}
function apply(){ensure();const name=q('#meTrack').value;if(!name)return alert('Valitse kappale.');let s=Math.max(0,(Number(q('#meStart').value)||1)-1),e=Math.max(s,(Number(q('#meEnd').value)||s+1)-1);s=Math.min(s,state.eights.length-1);e=Math.min(e,state.eights.length-1);snapshot();Object.values(state.eightMusicAssignments).filter(a=>!(a.endRow<s||a.startRow>e)).forEach(drop);const id=uid(),an=state.trackAnalysis?.[name],offset=Number(an?.oneOffset)||0,dur=(e-s+1)*spe();state.eightMusicAssignments[id]={id,trackName:name,startRow:s,endRow:e,sourceOffset:offset};for(let i=s;i<=e;i++)state.eights[i].music=name;state.audioTimeline.clips.push({id:uid(),assignmentId:id,type:'music',sourceName:name,name,start:s*spe(),sourceOffset:offset,duration:dur});q('#musicEightDlg').close();renderAll();scheduleSave()}
function remove(){const a=find(row);if(!a)return;snapshot();drop(a);q('#musicEightDlg').close();renderAll();scheduleSave()}
function enhance(){ensure();document.querySelectorAll('#eightBody tr').forEach((tr,r)=>{const input=tr.querySelector('.meta-input[data-field="music"]');if(!input)return;const a=find(r),td=input.closest('td'),b=document.createElement('button');b.type='button';b.dataset.musiceight=r;b.className='mini-btn';b.style.width='100%';b.style.textAlign='left';b.innerHTML=a?`🎵 ${a.trackName}<br><small>kasit ${a.startRow+1}–${a.endRow+1}</small>`:'+ Valitse musiikki';td.innerHTML='';td.appendChild(b)})}
function init(){dialog();enhance();const old=renderTable;renderTable=function(){old();enhance()};q('#eightBody')?.addEventListener('click',e=>{const b=e.target.closest('[data-musiceight]');if(b){e.preventDefault();e.stopPropagation();open(Number(b.dataset.musiceight))}});document.addEventListener('cheer-audio-restored',enhance)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
