(()=>{
const q=s=>document.querySelector(s);let row=0;let syncing=false;
function ensure(){state.eightMusicAssignments=state.eightMusicAssignments||{};state.audioTimeline=state.audioTimeline||{clips:[],zoom:1,snap:'beat'};state.audioTimeline.clips=state.audioTimeline.clips||[]}
function spb(){return 60/(Number(state.targetBpm)||147)}function spe(){return 8*spb()}
function rowsFor(a){let s=a.startEightId?state.eights.findIndex(x=>x.id===a.startEightId):-1,e=a.endEightId?state.eights.findIndex(x=>x.id===a.endEightId):-1;if(s<0)s=Math.max(0,Math.min(state.eights.length-1,Number(a.startRow)||0));if(e<0)e=Math.max(s,Math.min(state.eights.length-1,Number(a.endRow)||s));if(e<s)[s,e]=[e,s];return[s,e]}
function migrate(a){const[s,e]=rowsFor(a);a.startRow=s;a.endRow=e;a.startEightId=state.eights[s]?.id||a.startEightId||null;a.endEightId=state.eights[e]?.id||a.endEightId||null;a.startBeat=Math.max(1,Math.min(8,Number(a.startBeat)||1));a.endBeat=Math.max(1,Math.min(8,Number(a.endBeat)||8));if(a.followOne==null)a.followOne=true;return[s,e]}
function find(r){ensure();return Object.values(state.eightMusicAssignments).find(a=>{const[s,e]=rowsFor(a);return r>=s&&r<=e})}function clipFor(a){return state.audioTimeline.clips.find(c=>c.assignmentId===a.id)}
function timelineStart(a,s){return s*spe()+(a.startBeat-1)*spb()}function timelineEnd(a,e){return e*spe()+a.endBeat*spb()}
function syncAssignments({save=false}={}){if(syncing||!state?.eights?.length)return;syncing=true;try{ensure();const valid=new Set();for(const a of Object.values(state.eightMusicAssignments)){const[s,e]=migrate(a);valid.add(a.id);const an=state.trackAnalysis?.[a.trackName];if(a.followOne!==false&&Number.isFinite(Number(an?.oneOffset))&&!Number.isFinite(Number(a.sourceStart)))a.sourceStart=Math.max(0,Number(an.oneOffset));a.sourceStart=Math.max(0,Number(a.sourceStart??a.sourceOffset)||0);a.sourceEnd=Number.isFinite(Number(a.sourceEnd))?Math.max(a.sourceStart,Number(a.sourceEnd)):null;for(let i=s;i<=e;i++)state.eights[i].music=a.trackName;let c=clipFor(a);if(!c){c={id:uid(),assignmentId:a.id,type:'music',sourceName:a.trackName,name:a.trackName};state.audioTimeline.clips.push(c)}c.type='music';c.sourceName=a.trackName;c.name=a.trackName;c.start=timelineStart(a,s);const slotDur=Math.max(spb()/4,timelineEnd(a,e)-c.start);c.duration=slotDur;c.sourceOffset=a.sourceStart;if(a.sourceEnd!=null)c.sourceEnd=a.sourceEnd;else delete c.sourceEnd;if(!Number.isFinite(Number(c.volume)))c.volume=1;c.fadeIn=Math.max(0,Math.min(c.duration,Number(c.fadeIn)||0));c.fadeOut=Math.max(0,Math.min(c.duration,Number(c.fadeOut)||0))}state.audioTimeline.clips=state.audioTimeline.clips.filter(c=>!c.assignmentId||valid.has(c.assignmentId));if(save)scheduleSave()}finally{syncing=false}window.cheerAudioEditor?.renderTimeline?.()}
function dialog(){if(q('#musicEightDlg'))return;const d=document.createElement('dialog');d.id='musicEightDlg';d.innerHTML=`<form method="dialog" style="min-width:680px;max-width:820px;padding:20px;background:#0d1728;color:#fff"><h2>Lisää musiikki ohjelmaan</h2><p>Valitse sekä kappaleesta käytettävä kohta että ohjelman tarkka alku- ja loppulasku.</p><div style="display:grid;grid-template-columns:2fr 1fr 1fr;gap:10px"><label>Kappale<select id="meTrack"></select></label><label>Kappale alkaa (s)<input id="meSourceStart" type="number" min="0" step="0.01" value="0"></label><label>Kappale loppuu (s)<input id="meSourceEnd" type="number" min="0" step="0.01" placeholder="automaattinen"></label></div><div style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:10px;margin-top:12px"><label>Alkukasi<input id="meStart" type="number" min="1"></label><label>Alkulasku<select id="meStartBeat">${[1,2,3,4,5,6,7,8].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Loppukasi<input id="meEnd" type="number" min="1"></label><label>Loppulasku<select id="meEndBeat">${[1,2,3,4,5,6,7,8].map(x=>`<option${x===8?' selected':''}>${x}</option>`).join('')}</select></label></div><p style="opacity:.8">Esim. loppukasi 8 + loppulasku 6 = musiikki loppuu täsmälleen kasin 8 laskun 6 jälkeen.</p><div style="display:flex;gap:8px;align-items:center"><button type="button" id="mePreview" class="btn secondary">▶ Esikuuntele kohdasta</button><button type="button" id="meSetStart" class="btn secondary">Aseta soittimen aika alkuun</button><button type="button" id="meSetEnd" class="btn secondary">Aseta soittimen aika loppuun</button></div><p id="meInfo"></p><menu style="display:flex;gap:8px;justify-content:flex-end"><button value="cancel" class="btn secondary">Peruuta</button><button type="button" id="meRemove" class="btn secondary">Poista</button><button type="button" id="meApply" class="btn primary">Tallenna musiikki</button></menu></form>`;document.body.appendChild(d);q('#meApply').onclick=apply;q('#meRemove').onclick=remove;['#meTrack','#meStart','#meEnd','#meStartBeat','#meEndBeat','#meSourceStart','#meSourceEnd'].forEach(s=>q(s).addEventListener('input',info));q('#mePreview').onclick=preview;q('#meSetStart').onclick=()=>{q('#meSourceStart').value=(q('#audioPlayer')?.currentTime||0).toFixed(2);info()};q('#meSetEnd').onclick=()=>{q('#meSourceEnd').value=(q('#audioPlayer')?.currentTime||0).toFixed(2);info()}}
function fill(name=''){const s=q('#meTrack');s.innerHTML='<option value="">Valitse musiikki…</option>';for(const t of(state.tracks||[])){const o=document.createElement('option');o.value=t.name;o.textContent=t.name;s.appendChild(o)}if(name)s.value=name}
function info(){const s=Number(q('#meStart').value)||1,e=Math.max(s,Number(q('#meEnd').value)||s),sb=Number(q('#meStartBeat').value)||1,eb=Number(q('#meEndBeat').value)||8;const beats=Math.max(1,(e-s)*8+(eb-sb+1));const name=q('#meTrack').value,a=state.trackAnalysis?.[name],ss=Number(q('#meSourceStart').value)||0,se=Number(q('#meSourceEnd').value);q('#meInfo').textContent=`Ohjelmassa ${beats} laskua · ${(beats*spb()).toFixed(2)} s${Number.isFinite(se)&&se>ss?` · lähteestä ${(se-ss).toFixed(2)} s`:''}${a?.bpm?` · ${Number(a.bpm).toFixed(1)} → ${state.targetBpm} BPM`:''}`}
function preview(){const name=q('#meTrack').value,t=(state.tracks||[]).find(x=>x.name===name),p=q('#audioPlayer');if(!t||!p)return alert('Valitse kappale.');p.src=t.url;p.currentTime=Math.max(0,Number(q('#meSourceStart').value)||0);p.play().catch(()=>{})}
function open(r){ensure();syncAssignments();dialog();row=r;const a=find(r);fill(a?.trackName);const[s,e]=a?rowsFor(a):[r,r];q('#meStart').max=q('#meEnd').max=state.eights.length;q('#meStart').value=s+1;q('#meEnd').value=e+1;q('#meStartBeat').value=a?.startBeat||1;q('#meEndBeat').value=a?.endBeat||8;q('#meSourceStart').value=Number(a?.sourceStart??a?.sourceOffset??state.trackAnalysis?.[a?.trackName]?.oneOffset??0).toFixed(2);q('#meSourceEnd').value=a?.sourceEnd!=null?Number(a.sourceEnd).toFixed(2):'';q('#meRemove').disabled=!a;info();q('#musicEightDlg').showModal()}
function drop(a){if(!a)return;const[s,e]=rowsFor(a);delete state.eightMusicAssignments[a.id];state.audioTimeline.clips=state.audioTimeline.clips.filter(c=>c.assignmentId!==a.id);for(let i=s;i<=e&&i<state.eights.length;i++)if(state.eights[i].music===a.trackName)state.eights[i].music=''}
function apply(){ensure();const name=q('#meTrack').value;if(!name)return alert('Valitse kappale.');let s=Math.max(0,(Number(q('#meStart').value)||1)-1),e=Math.max(s,(Number(q('#meEnd').value)||s+1)-1);s=Math.min(s,state.eights.length-1);e=Math.min(e,state.eights.length-1);const sb=Number(q('#meStartBeat').value)||1,eb=Number(q('#meEndBeat').value)||8;if(s===e&&eb<sb)return alert('Loppulaskun pitää olla alkulaskun jälkeen.');snapshot();Object.values(state.eightMusicAssignments).filter(a=>{const[as,ae]=rowsFor(a);return !(ae<s||as>e)}).forEach(drop);const id=uid(),ss=Math.max(0,Number(q('#meSourceStart').value)||0),rawEnd=q('#meSourceEnd').value.trim(),se=rawEnd===''?null:Math.max(ss,Number(rawEnd)||ss);state.eightMusicAssignments[id]={id,trackName:name,startRow:s,endRow:e,startEightId:state.eights[s]?.id,endEightId:state.eights[e]?.id,startBeat:sb,endBeat:eb,sourceStart:ss,sourceEnd:se,followOne:false};for(let i=s;i<=e;i++)state.eights[i].music=name;syncAssignments();q('#musicEightDlg').close();renderAll();scheduleSave()}
function remove(){const a=find(row);if(!a)return;snapshot();drop(a);q('#musicEightDlg').close();renderAll();scheduleSave()}
function enhance(){ensure();syncAssignments();document.querySelectorAll('#eightBody tr').forEach((tr,r)=>{const input=tr.querySelector('.meta-input[data-field="music"]');if(!input)return;const a=find(r),td=input.closest('td'),b=document.createElement('button');b.type='button';b.dataset.musiceight=r;b.className='mini-btn';b.style.width='100%';b.style.textAlign='left';if(a){const[s,e]=rowsFor(a);b.innerHTML=`🎵 ${a.trackName}<br><small>${s+1}.${a.startBeat||1} → ${e+1}.${a.endBeat||8}</small>`}else b.textContent='+ Valitse musiikki';td.innerHTML='';td.appendChild(b)})}
function init(){dialog();syncAssignments();enhance();const old=renderTable;renderTable=function(){syncAssignments();old();enhance()};q('#eightBody')?.addEventListener('click',e=>{const b=e.target.closest('[data-musiceight]');if(b){e.preventDefault();e.stopPropagation();open(Number(b.dataset.musiceight))}});q('#targetBpm')?.addEventListener('input',()=>setTimeout(()=>syncAssignments({save:true}),0));document.addEventListener('cheer-audio-restored',()=>{syncAssignments();enhance()});window.addEventListener('cheer-track-analysis-changed',()=>syncAssignments({save:true}));window.cheerEightMusic={sync:syncAssignments,find,rowsFor}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();