(()=>{
const q=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const cache=new Map();
function ensure(){if(!state.audioTimeline)state.audioTimeline={clips:[],zoom:1,snap:'beat'};state.audioTimeline.clips=state.audioTimeline.clips||[];state.intelligentMix=state.intelligentMix||{plans:{}}}
function spb(){return 60/(Number(state.targetBpm)||147)}
function music(){return(state.audioTimeline.clips||[]).filter(c=>c.type==='music').sort((a,b)=>Number(a.start)-Number(b.start))}
function beatLabel(sec){const beat=Math.max(0,Math.round(sec/spb())),eight=Math.floor(beat/8)+1,count=beat%8+1;return`kasi ${eight} / lasku ${count}`}
function rate(c){return window.cheerTimelineAudioEngine?.rateFor?.(c)||1}
function track(c){return(state.tracks||[]).find(t=>t.name===c.sourceName)}
async function decode(t){if(cache.has(t.name))return cache.get(t.name);if(!t?.url)throw new Error('Lähdeaudiota ei löydy');const bytes=await fetch(t.url).then(r=>r.arrayBuffer()),ac=new(window.AudioContext||window.webkitAudioContext)();try{const b=await ac.decodeAudioData(bytes.slice(0));cache.set(t.name,b);return b}finally{ac.close().catch(()=>{})}}
function edgeEnergy(buf,time,windowSec=.16){const sr=buf.sampleRate,ch=buf.getChannelData(0),a=Math.max(0,Math.floor((time-windowSec/2)*sr)),b=Math.min(ch.length,Math.floor((time+windowSec/2)*sr));if(b<=a)return 0;let s=0,p=0,n=0;for(let i=a;i<b;i+=2){const v=ch[i];s+=v*v;p=Math.max(p,Math.abs(v));n++}return Math.min(1,Math.sqrt(s/Math.max(1,n))*.7+p*.3)}
async function analyzePair(a,b,i){const transition=Number(b.start)||0,endA=(Number(a.start)||0)+(Number(a.duration)||0),gap=transition-endA;let outEnergy=.5,inEnergy=.5;try{const ta=track(a),tb=track(b);if(ta&&tb){const[ba,bb]=await Promise.all([decode(ta),decode(tb)]);const at=(Number(a.sourceOffset)||0)+Math.max(0,transition-Number(a.start))*rate(a),bt=Number(b.sourceOffset)||0;outEnergy=edgeEnergy(ba,at);inEnergy=edgeEnergy(bb,bt)}}catch{}
const bpmA=Number(state.trackAnalysis?.[a.sourceName]?.bpm||state.trackAnalysis?.[a.sourceName]?.autoBpm)||0,bpmB=Number(state.trackAnalysis?.[b.sourceName]?.bpm||state.trackAnalysis?.[b.sourceName]?.autoBpm)||0,tempoDiff=bpmA&&bpmB?Math.abs(bpmA-bpmB)/Math.max(bpmA,bpmB):0;let style='beat-cut',reason='Tarkka cheer-leikkaus toimii hyvin laskurajalla.';if(Math.abs(gap)>.06){style='short-crossfade';reason=gap>0?'Musiikkien välissä on pieni aukko, joten lyhyt crossfade peittää sen.':'Musiikit ovat hieman päällekkäin, joten lyhyt crossfade tasaa vaihdon.'}else if(outEnergy>.58&&inEnergy>.58){style='impact-cut';reason='Molemmissa kohdissa on vahva transientti; nopea impact-tyylinen vaihto sopii tähän.'}else if(tempoDiff>.16){style='short-crossfade';reason='Tempoero on suuri; hyvin lyhyt crossfade on turvallisempi kuin kova leikkaus.'}
let score=100;score-=Math.min(35,Math.abs(gap)*120);score-=Math.min(20,tempoDiff*80);if(!bpmA||!bpmB)score-=15;score=Math.round(clamp(score,0,100));return{id:`${a.id}::${b.id}`,index:i,a,b,transition,gap,outEnergy,inEnergy,bpmA,bpmB,style,reason,score,label:beatLabel(transition)}}
async function analyzeAll(){ensure();const arr=music(),btn=q('#btnAnalyzeTransitions');if(arr.length<2){alert('Lisää vähintään kaksi musiikkia aikajanalle.');return[]}if(btn){btn.disabled=true;btn.textContent='⏳ Analysoidaan…'}const host=q('#intelligentMixResults');if(host)host.innerHTML='<div class="im-empty">Analysoidaan kappaleenvaihtoja…</div>';try{const plans=[];for(let i=0;i<arr.length-1;i++)plans.push(await analyzePair(arr[i],arr[i+1],i));state.intelligentMix.lastAnalysis=Date.now();state.intelligentMix.plans={};plans.forEach(p=>state.intelligentMix.plans[p.id]={style:p.style,score:p.score});render(plans);return plans}catch(err){console.error(err);if(host)host.innerHTML=`<div class="im-error">Analyysi epäonnistui: ${escapeHtml(err?.message||'tuntematon virhe')}</div>`;return[]}finally{if(btn){btn.disabled=false;btn.textContent='✨ Analysoi siirtymät'}}}
function applyPlan(p,style){const a=p.a,b=p.b,beat=spb();if(style==='beat-cut'){a.fadeOut=clamp(beat*.035,.015,.06);b.fadeIn=clamp(beat*.025,.01,.05);a.duration=Math.max(.03,p.transition-Number(a.start))}else if(style==='impact-cut'){a.fadeOut=clamp(beat*.02,.008,.035);b.fadeIn=clamp(beat*.012,.005,.025);a.duration=Math.max(.03,p.transition-Number(a.start))}else{const fade=clamp(beat*.55,.14,.32);a.duration=Math.max(.03,p.transition-Number(a.start)+fade);a.fadeOut=fade;b.fadeIn=fade}scheduleSave();window.cheerAudioEditor?.renderTimeline?.();window.cheerTimelineAudioEngine?.refreshInspector?.()}
function preview(p){const from=Math.max(0,p.transition-spb()*4);window.cheerAudioEditor?.seek?.(from,false);setTimeout(()=>{const btn=q('#btnTimelinePlay');if(btn&&!btn.textContent.includes('TAUKO'))btn.click()},80)}
function render(plans){const host=q('#intelligentMixResults');if(!host)return;if(!plans.length){host.innerHTML='<div class="im-empty">Ei analysoitavia siirtymiä.</div>';return}host.innerHTML=plans.map((p,i)=>`<div class="im-card" data-plan="${i}"><div class="im-head"><div><strong>${escapeHtml(p.a.sourceName)} → ${escapeHtml(p.b.sourceName)}</strong><span>${p.label}</span></div><div class="im-score ${p.score>=80?'good':p.score>=60?'mid':'bad'}">${p.score}/100</div></div><div class="im-meta">${p.bpmA?p.bpmA.toFixed(1):'?'} → ${p.bpmB?p.bpmB.toFixed(1):'?'} BPM · ${p.gap>0?'+':''}${p.gap.toFixed(3)} s · isku ulos ${Math.round(p.outEnergy*100)} % / sisään ${Math.round(p.inEnergy*100)} %</div><div class="im-reason">${escapeHtml(p.reason)}</div><div class="im-actions"><label>Siirtymä <select data-style="${i}"><option value="beat-cut" ${p.style==='beat-cut'?'selected':''}>Beat cut</option><option value="impact-cut" ${p.style==='impact-cut'?'selected':''}>Impact cut</option><option value="short-crossfade" ${p.style==='short-crossfade'?'selected':''}>Lyhyt crossfade</option></select></label><button class="mini-btn" data-preview="${i}">▶ Kuuntele vaihto</button><button class="mini-btn" data-apply="${i}">✓ Käytä tätä</button></div></div>`).join('');host.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>preview(plans[Number(b.dataset.preview)]));host.querySelectorAll('[data-apply]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.apply),style=host.querySelector(`[data-style="${i}"]`).value;snapshot();applyPlan(plans[i],style);b.textContent='✓ Käytössä'});state.intelligentMix._plans=plans}
function applyAll(){const plans=state.intelligentMix?._plans||[];if(!plans.length)return alert('Analysoi siirtymät ensin.');snapshot();for(let i=0;i<plans.length;i++){const sel=q(`#intelligentMixResults [data-style="${i}"]`);applyPlan(plans[i],sel?.value||plans[i].style)}alert('Ehdotetut siirtymät käytettiin. Kuuntele jokainen vaihto vielä erikseen.')}
function addUi(){const panel=q('#mixAssistant');if(!panel||q('#intelligentMixPanel'))return;const section=document.createElement('div');section.id='intelligentMixPanel';section.innerHTML=`<div class="im-title"><div><h3>Älykäs cheer-miksaus</h3><p>Analysoi jokaisen kappaleenvaihdon erikseen. Sovellus ehdottaa siirtymää, mutta ei muuta mitään ennen hyväksyntää.</p></div><div class="im-main-actions"><button id="btnAnalyzeTransitions" class="btn primary">✨ Analysoi siirtymät</button><button id="btnApplyAllSmart" class="mini-btn">✓ Käytä kaikki ehdotukset</button></div></div><div id="intelligentMixResults"><div class="im-empty">Paina “Analysoi siirtymät”.</div></div>`;panel.appendChild(section);q('#btnAnalyzeTransitions').onclick=analyzeAll;q('#btnApplyAllSmart').onclick=applyAll}
const style=document.createElement('style');style.textContent=`#intelligentMixPanel{margin-top:14px;padding-top:14px;border-top:1px solid rgba(148,163,184,.18)}.im-title,.im-head,.im-actions,.im-main-actions{display:flex;gap:10px;justify-content:space-between;align-items:center}.im-main-actions{justify-content:flex-end;flex-wrap:wrap}.im-title h3{margin:0 0 4px}.im-title p{margin:0;opacity:.75}.im-card{margin-top:10px;padding:11px;border:1px solid rgba(148,163,184,.18);border-radius:10px;background:rgba(15,23,42,.38)}.im-head>div:first-child{display:flex;flex-direction:column;gap:2px}.im-head span,.im-meta{font-size:12px;opacity:.72}.im-score{font-weight:800;padding:4px 8px;border-radius:999px}.im-score.good{background:rgba(16,185,129,.15)}.im-score.mid{background:rgba(245,158,11,.15)}.im-score.bad{background:rgba(239,68,68,.15)}.im-reason{margin:8px 0;font-size:13px}.im-actions{justify-content:flex-start;flex-wrap:wrap}.im-actions label{display:flex;align-items:center;gap:6px}.im-empty,.im-error{padding:10px;opacity:.75}.im-error{border-left:3px solid #ef4444;background:rgba(239,68,68,.08)}@media(max-width:800px){.im-title,.im-head{align-items:flex-start;flex-direction:column}.im-main-actions{justify-content:flex-start}}`;document.head.appendChild(style);
function init(){ensure();addUi();document.addEventListener('cheer-audio-restored',()=>setTimeout(addUi,100));window.cheerIntelligentMix={analyzeAll,applyAll}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();