const assert=require('node:assert/strict');
const fs=require('node:fs');

const ui=fs.readFileSync('competition-master-assessment-ui.js','utf8');
const workflow=fs.readFileSync('simple-workflow.js','utf8');

assert.ok(/getLastCompetitionMasterMetrics/.test(ui),'assessment UI must read measured competition master metrics from export API');
assert.ok(/getLastCompetitionMasterReadiness/.test(ui),'assessment UI must read competition readiness from export API');
assert.ok(/getLastCompetitionMasterPreview/.test(ui),'assessment UI must read advisory master preview from export API');
assert.ok(/getLastCompetitionMasterFinalCheck/.test(ui),'assessment UI must read the final-check result from export API');
assert.ok(/True peak/.test(ui)&&/Integrated loudness/.test(ui)&&/LRA/.test(ui),'assessment UI must surface true peak, integrated loudness and LRA');
assert.ok(/preview-ready/.test(ui)&&/preview-approved/.test(ui)&&/review-required/.test(ui)&&/blocked/.test(ui),'assessment UI must distinguish ready, final-check approved, review-required and blocked states');
assert.ok(/voiceover-hold/.test(ui)&&/peak-headroom/.test(ui)&&/section-balance/.test(ui),'assessment UI must translate key competition-master recommendations for the user');
assert.ok(/Osakohtaiset clarity-havainnot/.test(ui),'assessment UI must provide a dedicated section-aware clarity findings area');
assert.ok(/sectionIssues/.test(ui),'assessment UI must render section issues produced by competition final-check');
assert.ok(/voiceover clarity/.test(ui)&&/FX clarity/.test(ui),'assessment UI must identify whether voiceover or FX clarity failed in a cheer section');
assert.ok(/sectionId/.test(ui)&&/data.*section/i.test(ui),'section-aware findings must retain the source section identity for later editor navigation');
assert.ok(/focusStartSeconds/.test(ui)&&/data.*focus/i.test(ui),'section-aware findings must retain the weakest measured clarity-window timing');
assert.ok(/focusKind/.test(ui),'section findings must retain whether the weakest focus is voiceover or FX');
assert.ok(/focusScore/.test(ui)&&/focusMinScore/.test(ui),'section findings must retain exact measured clarity score and acceptance threshold');
assert.ok(/dataset\.focusScore/.test(ui)&&/dataset\.focusMinScore/.test(ui),'rendered findings must expose diagnostic score and threshold for inspection');
assert.ok(/correctionGuidanceLabel/.test(ui)&&/correctionGuidance/.test(ui),'assessment UI must render structured correction guidance from final-check');
assert.ok(/kevennä musiikkia paikallisesti voiceoverin alta/.test(ui),'voiceover guidance must prefer a local music-bed correction before global mix changes');
assert.ok(/kevennä tai lyhennä peittävää FX:ää/.test(ui),'FX guidance must recommend reducing local masking rather than changing the whole master');
assert.ok(/neuvoa-antavia eivätkä muuta audiota automaattisesti/.test(ui),'correction guidance must explicitly remain advisory and non-automatic');
assert.ok(/role','note'/.test(ui)||/setAttribute\('role','note'\)/.test(ui),'correction guidance must be exposed as an assistive note');
assert.ok(/focusSectionIssue/.test(ui),'assessment UI must expose a focused section navigation action');
assert.ok(/cheerAudioEditor/.test(ui)&&/\.seek\(/.test(ui),'section navigation must use the existing audio editor seek API');
assert.ok(/audioWorkspace/.test(ui)&&/scrollIntoView/.test(ui),'section navigation must bring the audio workspace into view');
assert.ok(/score:issue\?\.focusScore/.test(ui)&&/minScore:issue\?\.focusMinScore/.test(ui),'section navigation must pass exact diagnostics to the timeline highlight');
assert.ok(/competition-master-section-jump/.test(ui)&&/addEventListener\('click'/.test(ui),'timed section findings must be rendered as explicit clickable controls');
assert.ok(/heikoimpaan mitattuun voiceover- tai FX-kohtaan/.test(ui),'UI must explain that findings jump to the precise measured problem window');
assert.ok(/clarity-score sekä hyväksymisraja/.test(ui),'UI must explain that the highlight shows the measured score and acceptance threshold');
assert.ok(/Siirry heikoimpaan/.test(ui),'precise clarity navigation must have an accessible Finnish action label');
assert.ok(/Final-check ei löytänyt kilpailumasteria estäviä riskejä/.test(ui),'approved final-check must have a clear non-destructive user-facing state');
assert.ok(/ei-tuhoava tarkistus/.test(ui),'assessment UI must clearly communicate non-destructive behavior');
assert.ok(!/applyMasterHeadroom|fromAudioBuffer|renderProject|createGain|DynamicsCompressor|normalize/i.test(ui.replace(/normalisoi/g,'')),'assessment UI must not perform audio mastering or rendering');
assert.ok(/MutationObserver/.test(ui),'assessment UI must refresh when export status changes');
assert.ok(/competition-master-section-clarity-core\.js/.test(workflow),'simple workflow must load section-aware clarity before export analysis');
assert.ok(/data-competition-master-section-clarity/.test(workflow),'section-aware clarity loader must prevent duplicate script insertion');
assert.ok(/competition-master-assessment-ui\.js/.test(workflow),'simple workflow must load the assessment UI module');
assert.ok(/data-competition-master-assessment/.test(workflow),'assessment UI loader must prevent duplicate script insertion');
console.log('competition-master-assessment-ui: final-check findings show precise, advisory local correction guidance without modifying audio');
