const assert=require('node:assert/strict');
const fs=require('node:fs');
const exportJs=fs.readFileSync('mix-export.js','utf8');
const offline=fs.readFileSync('offline-render.js','utf8');
const index=fs.readFileSync('index.html','utf8');

assert.ok(!/MediaRecorder/.test(exportJs),'production WAV export must not use MediaRecorder');
assert.ok(!/audio\/webm|codecs=opus|audioBitsPerSecond/.test(exportJs),'production WAV export must not contain lossy WebM/Opus recorder path');
assert.ok(/CheerOfflineRenderer\.renderProject/.test(exportJs),'WAV export must use offline PCM renderer');
assert.ok(/CheerWav24\.fromAudioBuffer/.test(exportJs),'WAV export must encode rendered PCM directly as 24-bit WAV');
assert.ok(/competition-master-metrics-core\.js/.test(exportJs),'competition master metrics core must be available to the export path');
assert.ok(/competition-master-input-core\.js/.test(exportJs),'competition master input core must be available to the export path');
assert.ok(/competition-master-readiness-core\.js/.test(exportJs),'competition master readiness core must be available to the export path');
assert.ok(/competition-master-export-readiness-core\.js/.test(exportJs),'export readiness bridge must be available to the export path');
assert.ok(/measureCompetitionMaster\(rendered\)/.test(exportJs),'rendered post-voiceover PCM must be measured before final export');
assert.ok(/evaluateCompetitionMasterReadiness\(competition\?\.metrics\)/.test(exportJs),'measured post-voiceover metrics must feed readiness evaluation');
assert.ok(/getLastCompetitionMasterMetrics/.test(exportJs),'latest competition master input metrics must remain available for readiness integration');
assert.ok(/getLastCompetitionMasterReadiness/.test(exportJs),'latest competition master readiness must remain available after export');
const renderAt=exportJs.indexOf('CheerOfflineRenderer.renderProject'),measureAt=exportJs.indexOf('measureCompetitionMaster(rendered)'),readinessAt=exportJs.indexOf('evaluateCompetitionMasterReadiness(competition?.metrics)'),headroomAt=exportJs.indexOf('applyMasterHeadroom(rendered');
assert.ok(renderAt>=0&&measureAt>renderAt&&readinessAt>measureAt&&headroomAt>readinessAt,'competition metrics and readiness must evaluate the untouched post-voiceover render before headroom gain changes PCM');
assert.ok(/SAMPLE_RATE=48000/.test(offline),'offline renderer must be fixed at 48 kHz');
assert.ok(/CHANNELS=2/.test(offline),'offline renderer must be stereo');
assert.ok(/OfflineAudioContext/.test(offline),'offline renderer must use OfflineAudioContext');
assert.ok(!/MediaRecorder/.test(offline),'offline renderer must not use MediaRecorder');
assert.ok(/CheerTimeStretch/.test(offline),'offline renderer must use the shared pitch-preserving time-stretch core');

const dsp=index.indexOf('mix-dsp-core.js'),stretch=index.indexOf('time-stretch-core.js'),timing=index.indexOf('audio-timing-core.js'),timeline=index.indexOf('timeline-audio-engine.js'),wav=index.indexOf('wav24.js'),renderer=index.indexOf('offline-render.js'),exp=index.indexOf('mix-export.js');
assert.ok(dsp>=0&&stretch>dsp&&timing>stretch,'shared DSP and time-stretch must load before timing/playback core');
assert.ok(timeline>timing,'timeline AudioContext engine must load after shared timing/stretch cores');
assert.ok(wav>=0&&renderer>wav&&exp>renderer,'WAV encoder and offline renderer must load before export UI');
console.log('lossless-export-contract: OfflineAudioContext -> post-voiceover metrics -> competition readiness -> headroom -> 24-bit WAV path enforced');