const assert=require('node:assert/strict');
const fs=require('node:fs');
const exportJs=fs.readFileSync('mix-export.js','utf8');
const offline=fs.readFileSync('offline-render.js','utf8');
const index=fs.readFileSync('index.html','utf8');

assert.ok(!/MediaRecorder/.test(exportJs),'production WAV export must not use MediaRecorder');
assert.ok(!/audio\/webm|codecs=opus|audioBitsPerSecond/.test(exportJs),'production WAV export must not contain lossy WebM/Opus recorder path');
assert.ok(/CheerOfflineRenderer\.renderProject/.test(exportJs),'WAV export must use offline PCM renderer');
assert.ok(/CheerWav24\.fromAudioBuffer/.test(exportJs),'WAV export must encode rendered PCM directly as 24-bit WAV');
assert.ok(/competition-master-metrics-core\.js/.test(exportJs),'competition master metrics core must be available to the export path');
assert.ok(/competition-master-clarity-metrics-core\.js/.test(exportJs),'competition clarity metrics core must be available to the export path');
assert.ok(/competition-master-clarity-windows-core\.js/.test(exportJs),'competition clarity window derivation must be available to the export path');
assert.ok(/competition-master-input-core\.js/.test(exportJs),'competition master input core must be available to the export path');
assert.ok(/competition-master-readiness-core\.js/.test(exportJs),'competition master readiness core must be available to the export path');
assert.ok(/competition-master-preview-core\.js/.test(exportJs),'competition master preview core must be available to the export path');
assert.ok(/competition-master-final-check-core\.js/.test(exportJs),'competition master final-check core must be available to the export path');
assert.ok(/competition-master-export-readiness-core\.js/.test(exportJs),'export readiness bridge must be available to the export path');
assert.ok(/measureCompetitionMaster\(rendered\)/.test(exportJs),'rendered post-voiceover PCM must be measured before final export');
assert.ok(/measureCompetitionClarity\(rendered,competition\.metrics\)/.test(exportJs),'rendered post-voiceover PCM must feed voiceover/FX clarity measurement');
assert.ok(/buildCompetitionClarityWindows\(state,window\.CheerFxRenderCore\|\|null\)/.test(exportJs),'clarity windows must derive from actual timeline voiceovers and rendered Cheer FX sources');
assert.ok(/mergeIntoMasterMetrics\(metrics,measurement\)/.test(exportJs),'clarity scores must merge into the same master metrics package consumed by final check');
assert.ok(/evaluateCompetitionMasterReadiness\(competition\?\.metrics\)/.test(exportJs),'clarity-enriched post-voiceover metrics must feed readiness evaluation');
assert.ok(/previewCore:preview/.test(exportJs),'runtime readiness evaluation must pass the competition preview core to the bridge');
assert.ok(/buildCompetitionMasterFinalCheck/.test(exportJs),'runtime export path must evaluate the competition final check');
assert.ok(/lastCompetitionMasterClarity=measurement/.test(exportJs),'latest rendered clarity measurement must be retained after export analysis');
assert.ok(/lastCompetitionMasterPreview=result\?\.preview\|\|null/.test(exportJs),'latest competition master preview must be retained after evaluation');
assert.ok(/lastCompetitionMasterFinalCheck=result\?\.readiness&&result\?\.preview/.test(exportJs),'latest competition master final check must be retained after readiness and preview');
assert.ok(/getLastCompetitionMasterMetrics/.test(exportJs),'latest competition master input metrics must remain available for readiness integration');
assert.ok(/getLastCompetitionMasterClarity/.test(exportJs),'latest post-mix clarity measurement must remain available after export');
assert.ok(/getLastCompetitionMasterReadiness/.test(exportJs),'latest competition master readiness must remain available after export');
assert.ok(/getLastCompetitionMasterPreview/.test(exportJs),'latest advisory competition master preview must remain available after export');
assert.ok(/getLastCompetitionMasterFinalCheck/.test(exportJs),'latest advisory competition master final check must remain available after export');
assert.ok(/clarityInfo=lastCompetitionMasterClarity/.test(exportJs),'export status must surface measured voiceover and FX clarity scores');
assert.ok(/previewInfo=readinessResult\?\.preview/.test(exportJs),'export status must surface the advisory preview state');
assert.ok(/finalCheckInfo=readinessResult\?\.finalCheck/.test(exportJs),'export status must surface the advisory final-check state');
const renderAt=exportJs.indexOf('CheerOfflineRenderer.renderProject'),measureAt=exportJs.indexOf('measureCompetitionMaster(rendered)'),clarityAt=exportJs.indexOf('measureCompetitionClarity(rendered,competition.metrics)'),readinessAt=exportJs.indexOf('evaluateCompetitionMasterReadiness(competition?.metrics)'),finalCheckAt=exportJs.indexOf('buildCompetitionMasterFinalCheck'),headroomAt=exportJs.indexOf('applyMasterHeadroom(rendered');
assert.ok(renderAt>=0&&measureAt>renderAt&&clarityAt>measureAt&&readinessAt>clarityAt&&finalCheckAt>=0&&headroomAt>readinessAt,'competition metrics, clarity, readiness, preview and final check must evaluate the untouched post-voiceover render before headroom gain changes PCM');
assert.ok(/SAMPLE_RATE=48000/.test(offline),'offline renderer must be fixed at 48 kHz');
assert.ok(/CHANNELS=2/.test(offline),'offline renderer must be stereo');
assert.ok(/OfflineAudioContext/.test(offline),'offline renderer must use OfflineAudioContext');
assert.ok(!/MediaRecorder/.test(offline),'offline renderer must not use MediaRecorder');
assert.ok(/CheerTimeStretch/.test(offline),'offline renderer must use the shared pitch-preserving time-stretch core');

const dsp=index.indexOf('mix-dsp-core.js'),stretch=index.indexOf('time-stretch-core.js'),timing=index.indexOf('audio-timing-core.js'),timeline=index.indexOf('timeline-audio-engine.js'),wav=index.indexOf('wav24.js'),renderer=index.indexOf('offline-render.js'),exp=index.indexOf('mix-export.js');
assert.ok(dsp>=0&&stretch>dsp&&timing>stretch,'shared DSP and time-stretch must load before timing/playback core');
assert.ok(timeline>timing,'timeline AudioContext engine must load after shared timing/stretch cores');
assert.ok(wav>=0&&renderer>wav&&exp>renderer,'WAV encoder and offline renderer must load before export UI');
console.log('lossless-export-contract: OfflineAudioContext -> post-voiceover metrics -> voice/FX clarity -> competition readiness -> advisory preview -> advisory final-check -> headroom -> 24-bit WAV path enforced');
